[project]
name = "iceberg-sandbox"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.12.*"
jupyter = ">=1.0.0,<2"
pyiceberg = ">=0.7.0,<0.8"
black = ">=24.4.2,<25"
isort = ">=5.13.2,<6"
mypy = ">=1.10.1,<2"
tabulate = ">=0.9.0,<0.10"
pandas = ">=2.2.2,<3"
awscli = "2.*"
boto3 = ">=1.34.131,<2"
mypy-boto3-glue = ">=1.34.143,<2"
s3fs = ">=2023.12.2,<2024"
duckdb = ">=0.10.3,<0.11"
pyarrow = ">=16.1.0,<17"
python-snappy = ">=0.7.2,<0.8"
aiobotocore = ">=2.13.1,<3"
