name: Build Workflow

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "refs/tags/**"

jobs:
  call-build-job:
    uses: ./.github/workflows/build.yml # Reuse the build job from the build.yml file
