name: Release Workflow

on:
  push:
    tags:
      - '**'

jobs:
  call-build-job:
    uses: ./.github/workflows/build.yaml # Reuse the build job from the build.yaml file

  release:
    needs: call-build-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: dist

      - name: List Artifact Contents
        run: ls -R dist

      - name: Create GitHub Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          name: ${{ env.GITHUB_WORKFLOW }}
          files: dist/*
